config/routes.rb
Rails.application.routes.draw do
  resources :shopping_carts
  resources :orders
  resources :products
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord	
	has_many :product_shopping_carts
	has_many :products , through: :product_shopping_carts
	belongs_to :user
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_shopping_cart, only: %i[ show edit update destroy ]
  before_action :find_user, :find_product, only: %i[ new ]
  # GET /shopping_carts or /shopping_carts.json
  def index
    # @shopping_carts = ShoppingCart.all
    @user=User.first
    @shopping_cart= @user.shopping_cart
    @products= @shopping_cart.products
  end

  # GET /shopping_carts/1 or /shopping_carts/1.json
  def show
  end

  # GET /shopping_carts/new
  def new
  
    @shopping_cart = ShoppingCart.new

  end

  # GET /shopping_carts/1/edit
  def edit
  end

  # POST /shopping_carts or /shopping_carts.json
  def create
    
    # @shopping_cart = ShoppingCart.new(shopping_cart_params)
    @shopping_cart= User.first.shopping_cart
    # respond_to do |format|
    #   if @shopping_cart.save
        # binding.pry
        @shopping_cart.product_shopping_carts.create(product_shopping_cart_params)
       redirect_to shopping_carts_url,notice: "Shopping cart was successfully created." 
        # format.json { render :show, status: :created, location: @shopping_cart }
      # else
      #   format.html { render :new, status: :unprocessable_entity }
      #   format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      # end
    # end
  end

  # PATCH/PUT /shopping_carts/1 or /shopping_carts/1.json
  def update
    respond_to do |format|
      if @shopping_cart.update(shopping_cart_params)
        format.html { redirect_to shopping_cart_url(@shopping_cart), notice: "Shopping cart was successfully updated." }
        format.json { render :show, status: :ok, location: @shopping_cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_carts/1 or /shopping_carts/1.json
  def destroy
    @shopping_cart.destroy

    respond_to do |format|
      format.html { redirect_to shopping_carts_url, notice: "Shopping cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_cart
      @shopping_cart = ShoppingCart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shopping_cart_params
      params.require(:shopping_cart).permit( :user_id, :product_id)
    end

    def product_shopping_cart_params
       params.require(:shopping_cart).permit( :product_id, :quantity)
      # params.fetch(:user_id, :product_id, :quantity)
    end

    def find_user
      @user= User.find(params[:user_id])
    end

    def find_product
      @product= Product.find(params[:product_id])
    end
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
	def find_quantity(product_id,shopping_cart_id)
		ProductShoppingCart.where(product_id: product_id,shopping_cart_id:shopping_cart_id).first.quantity
	end

	def find_subtotal(products,shopping_cart_id)
		total=0
		products.each do|product|
			total+= product.price* find_quantity(product.id,shopping_cart_id)
		end
		return total
	end
end

app/views/shopping_carts/_form.html.erb
<%= form_with(model: shopping_cart) do |form| %>
  <% if shopping_cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shopping_cart.errors.count, "error") %> prohibited this shopping_cart from being saved:</h2>

      <ul>
        <% shopping_cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
   <%= form.label :quantity, style: "display: block" %>
   <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.hidden_field :user_id , value:@user.id%>
    <%= form.hidden_field :product_id , value: @product.id%>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shopping_carts/_shopping_cart.html.erb
<div id="<%= dom_id shopping_cart %>">
<% @products.each_with_index do |product,index| %>
	<p>
    <strong>Product Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%#= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%#= product.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%#= product.price %>
  </p>
   <p>
    <strong>Total:</strong>
    <%#= product.price %>
  </p>
<%end%>
</div>

app/views/shopping_carts/edit.html.erb
<h1>Editing shopping cart</h1>

<%= render "form", shopping_cart: @shopping_cart %>

<br>

<div>
  <%= link_to "Show this shopping cart", @shopping_cart %> |
  <%= link_to "Back to shopping carts", shopping_carts_path %>
</div>

app/views/shopping_carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shopping carts</h1>

<div id="shopping_carts">
  <%# @shopping_carts.each do |shopping_cart| %>
  <% @shopping_cart.products.each_with_index do |product,index| %>
  
    <p>
    <strong>Product Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
 |
    <strong>Quantity:</strong>
    <%= find_quantity(product.id,@shopping_cart.id) %>
  |
    <strong>Total:</strong>
    <%= product.price*find_quantity(product.id,@shopping_cart.id) %>
  </p>
    <%end%>
</div>
<div> <strong>Subtotal: <%= find_subtotal(@shopping_cart.products,@shopping_cart.id) %></strong></div>
<%= link_to "Add Another item", products_path %>
</br>
<button>Proceed payment</button>

app/views/shopping_carts/new.html.erb
<h1><%= @product.name %></h1>
<p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @product.price %>
  </p>
<%= render "form", shopping_cart: @shopping_cart %>

<br>

<div>
  <%= link_to "Back to shopping carts", shopping_carts_path %>
</div>

app/views/shopping_carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shopping_cart %>

<div>
  <%= link_to "Edit this shopping cart", edit_shopping_cart_path(@shopping_cart) %> |
  <%= link_to "Back to shopping carts", shopping_carts_path %>

  <%= button_to "Destroy this shopping cart", @shopping_cart, method: :delete %>
</div>