config/routes.rb
Rails.application.routes.draw do
  resources :shopping_carts
  resources :orders
  resources :products
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/order.rb
class Order < ApplicationRecord
	# has_many :products
	has_many :product_orders
	has_many :products , through: :product_orders
	belongs_to :user 
	# belongs_to :products
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :find_user, :find_product, only: %i[ new ]
  # GET /orders or /orders.json
  def index
    @orders = Order.all
    # @total_products_in_the_last_order= current_user.order.last.products
    # @total_amount_for_last_order= current_user.order.last.products.pluck(:price).inject(0,:+)

  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        # binding.pry
        # ProductOrder.create(product_order_params)
        @order.product_orders.create(product_order_params)
        format.html { redirect_to orders_url, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:total, :status, :user_id, :product_id)
    end

    def product_order_params
       params.require(:order).permit( :product_id, :quantity)
      # params.fetch(:user_id, :product_id, :quantity)
    end
    def find_user
      @user= User.find(params[:user_id])
    end

    def find_product
      @product= Product.find(params[:product_id])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
	def find_quantity(product_id,order_id)
		ProductOrder.where(product_id: product_id,order_id:order_id).first.quantity
	end
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <div>
   <%= form.label :quantity, style: "display: block" %>
   <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.hidden_field :user_id , value:@user.id%>
    <%= form.hidden_field :product_id , value: @product.id%>
  </div>

  <div>
    <%#= form.label :total, style: "display: block" %>
    <%#= form.number_field :total %>
  </div>

  <div>
    <%#= form.label :status, style: "display: block" %>
    <%#= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Order:</strong>
    <%= order.id %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each_with_index do |order,index| %>
    <%= render order %>
    <p>
      <%= link_to "Show this Order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", products_path %>

app/views/orders/new.html.erb
<h1><%= @product.name %></h1>
<p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @product.price %>
  </p>
<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="orders">
  <% @order.products.each do |product| %>
    <p>
    <strong>Product Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= find_quantity(product.id,@order.id) %>
  </p>
   <p>
    <strong>Total:</strong>
    <%= product.price*find_quantity(product.id,@order.id) %>
  </p>
  <% end %>
</div>

<div>
  <%#= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Remove order", @order, method: :delete %>
  <button>Proceed payment</button>
</div>